### ISSUE TITLE
IE8 problems - geosilk.css

### ISSUE THREAD

**Issue by wolwin** [geops/ole#31]
Using IE8 with the oleditor: it shows a grey line instead of the icon toolbar - also there are some css quirks. I've done a review of a new 'default-oleditor.css' file that will fix the main issues without any code change.

**Comment by lb1c** [comment]
Thanks for the report. We wont support IE8 actively, but pull requests are welcome. 
So i'm closing this issue now as WONTFIX for now, but feel free to reopen, if you want to contribute a fix.
