### ISSUE TITLE
Upgrade to OL3?

### ISSUE THREAD

**Issue by aleksandervines** [geops/ole#33]
Just a suggestion, OL3 may not have the required functionality supported for OLE (I haven't looked into it yet). I will, however, look into making a similar application based on OL3 in the near future if the time permits it.

**Comment by blazeeboy** [comment]
So any updates to this issue? as i think i'll need to use OLE with OL3

**Comment by AugustusKling** [comment]
See https://github.com/geops/ole3 but mind Jan Vogt's comment in https://github.com/geops/ole3/issues/1#issuecomment-124459797:
> […] this project is in a very early development state and certainly not ready for productive use […] if you still want to use ole3 in this early stage, you can just use the ready compiled ole3.js in the dist folder which I just added to the repo. Nevertheless, I strongly suggest at this point using more matured projects such as geops/ole for openlayers 2.

**Comment by lb1c** [comment]
A reimplementation of the OLE is in progress and will be released soon. This new version will be support the latest version of OL (currently OL4).
So there will be no further effort to support OL3 in this repo.
