### ISSUE TITLE
Use the ModifyFeature on Labels (DrawText) disappears the text

### ISSUE THREAD

**Issue by schildmi** [geops/ole#34]
Hi all,
I'm new on working with OpenLayers and the ole-editor. I think I find a mistake in the ole-editor.

If I set a label with the DrawText-Function on the map and after that use the ModifyFeature to change that text, the text disappears and instead of the text it appears only a point.

I think there would be two possible solutions. The first one ist to disallow the modifying of text. I could delete the "wrong" text and draw a new one. The second solution could be the possible to really modifiy the text by using the drawtext-function.

I'm sorry, but by now I don't understand this software enough to do it on my own.

It would be great, if someone can help me. 

Thanks a lot!

Michael

**Comment by gdherbert** [comment]
This appears to be a drawing issue, if you use the modify tool you can only modify the geometry. The text disappears. If you click the select tool and click the text "point" again, the text will redraw.

**Comment by lb1c** [comment]
Closing since this project is not maintained any longer.
Please visit https://github.com/geops/ole2
