### ISSUE TITLE
Saving multiple geometry types with Geoserver

### ISSUE THREAD

**Issue by 4quet** [geops/ole#40]
Hi,

I use OLE with Geoserver and WFS-T like shown in the example "wfs.html" and I would like to save every features (of every type: point, line and polygon) created with OLE in my PostGIS database. Do you have tips to accomplish that ? The problem being that the OLE instance accepts only one editLayer which has to be a 'point' OR 'line' OR 'polygon' vector layer.
I already thought about a few possibilities:

I could use a layer with "GeometryCollection" type to save every kind of features, I don't know if OLE supports this ?

I could also try to create multiple instances of OLE in my javascript, but it sounds pretty tricky. Having one toolbar redirecting to multiple editor instances might be possible ? But I have no idea how to do that.

Any help is welcome.

**Comment by AugustusKling** [comment]
You can have a single edit layer that supports multiple feature types as shown on http://ole.geops.de/. This example uses `localStorage` to persist the features like so (`d` being the `OpenLayers.Editor` instance):
```
  var e=new OpenLayers.Format.GeoJSON();
  ...
  d.editLayer.events.register("featureadded",this,function(g,h){
    localStorage["ole.map.features"]=e.write(d.editLayer.features)
  });
  d.editLayer.events.register("featureremoved",this,function(g,h){
    localStorage["ole.map.features"]=e.write(d.editLayer.features)
  });
  d.editLayer.events.register("afterfeaturemodified",this,function(g,h){
    localStorage["ole.map.features"]=e.write(d.editLayer.features)
  });
```
Thus OLE is able to work with multiple feature types in a single edit layer but an appropriate protocol needs to be used or loading and saving the data must be handled in your own code. I'm not aware of a means to use multiple edit layers with OLE.

**Comment by 4quet** [comment]
Thank you for your answer. Indeed `localStorage` is a solution to support multiple feature types, but the layer is "attached" to the browser and cannot be accessed by another user of my webapp. I'd like to make the `editLayer` accessible to multiple users, that's why I have to use Geoserver and PostGIS.

I'll keep looking for another solution :)

**Comment by AugustusKling** [comment]
The code from the previous comment generates GeoJSON and stores it into `localStorage` but there is no need to store it in `localStorage` – storing the GeoJSON on a server is possible, too. You can also replace the use of `OpenLayers.Format.GeoJSON` in the code from the comment with any implementation of `OpenLayers.Format`.

**Comment by 4quet** [comment]
Oh OK, I'll try this then, thank you !
