### ISSUE TITLE
Show distance from snipping point 

### ISSUE THREAD

**Issue by am2222** [geops/ole#44]
Hi,
Is there any way to show distance from snipping points on mouse? Sth like autocad or even if user types a value it draws lines in its entered distance?

**Comment by am2222** [comment]
@lb1c hi, I think I had too open this issue in OLE2 repository,shouldn't I?

**Comment by friedjoff** [comment]
There is no simple way to achive this right now. New features will go into OLE2, unless we get pull requests. So better open an issue there.
